#!/bin/env bash

# Kill SayMore b/c it starts as part of install in addition to run,
#   which doesn't allow pre-start script to run. The launch script 
#   will start it again, at the correct time.
pkill SayMore.exe

# Set Winver to 10.
"$WINELOADER" winecfg /v win10

# Change DPI (set in setup hook).
hex_dpi=$(printf '%.8X\n' "$WINEDPI")

echo "REGEDIT4

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Hardware Profiles\Current\Software\Fonts]
\"LogPixels\"=dword:$hex_dpi
" > sysdpi.reg

echo "REGEDIT4

[HKEY_CURRENT_USER\Control Panel\Desktop]
\"LogPixels\"=dword:$hex_dpi
" > usrdpi.reg

for r in usrdpi.reg sysdpi.reg; do
   "$WINELOADER" regedit "$r"
   rm -f "$r"
done

# Create initial Saymore.settings to allow overriding it's default values.
mkdir -p "${WINEPREFIX}/drive_c/users/nate/AppData/Local/SayMore"
sm_settings="${WINEPREFIX}/drive_c/users/nate/AppData/Local/SayMore/SayMore.settings"

if [[ ! -f "$sm_settings" ]]; then
  echo -e "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<Settings>
  <FirstTimeRun>True</FirstTimeRun>
  <SessionScreenComponentsSplitterPos>319</SessionScreenComponentsSplitterPos>
  <PersonContributionColumns>200,120,80,200</PersonContributionColumns>
  <AnnotationEditorVideoWindowYtoXRatio>0.75</AnnotationEditorVideoWindowYtoXRatio>
  <PersonCustomFieldsGrid />
  <ProjectWindow />
  <UnknownFileFieldsGrid />
  <SessionRecorderDlg />
  <PersonScreenComponentsSplitterPos>319</PersonScreenComponentsSplitterPos>
  <SessionScreenComponentGrid />
  <MediaFileMoreInfoDlg />
  <PersonListGrid />
  <SessionsListGrid />
  <ProjectOtherDocumentsComponentGrid />
  <DefaultSegmentationMethod />
  <NewSessionsFromFilesLastFolder />
  <FreeTranslationWsForFWInterlinearExport />
  <UserInterfaceLanguage>en</UserInterfaceLanguage>
  <NewSessionsFromFilesDlgComponentGrid />
  <PersonScreenComponentGrid />
  <ImageFileFieldsGrid />
  <AllowStatisticsChartLabelsToWrap />
  <VideoFileFieldsGrid />
  <SessionScreenElementsListSplitterPos>578</SessionScreenElementsListSplitterPos>
  <DefaultFolderForNewProjects />
  <ContributorsGrid />
  <SessionCustomFieldsGrid />
  <LastFolderForComponentFileAdd />
  <ArchivingDialog />
  <ShowFFmpegDetailsWhenConvertingMedia />
  <ProgramToLaunchForIMDIPackage>Arbil\\\\arbil-stable.exe</ProgramToLaunchForIMDIPackage>
  <NeedUpgrade>False</NeedUpgrade>
  <MediaPlayerVolume>-1</MediaPlayerVolume>
  <AnnotationEditorSpiltterPos />
  <SegmentGrid />
  <AudioFileFieldsGrid />
  <ManualSegmenterDlg />
  <AnnotationEditorPlaybackSpeedIndex>0</AnnotationEditorPlaybackSpeedIndex>
  <LocalizationDlgSettings />
  <ConvertMediaDlg />
  <TranscriptionWsForFWInterlinearExport />
  <TranslationPlaybackType>4</TranslationPlaybackType>
  <NewSessionsFromFilesDlg />
  <ZoomPercentageInAnnotationRecordingDlg>100</ZoomPercentageInAnnotationRecordingDlg>
  <ZoomPercentageInManualSegmenterDlg>100</ZoomPercentageInManualSegmenterDlg>
  <ProjectDescriptionDocumentsComponentGrid />
  <PersonScreenElementListSpiltterPos>578</PersonScreenElementListSpiltterPos>
  <WelcomeDialog />
  <TranscriptionPlaybackType>1</TranscriptionPlaybackType>
  <MPlayerDebuggingOutputWindow />
  <OralAnnotationRecorderDlg />
  <MRUList type=\"System.Collections.Specialized.StringCollection\" />
</Settings>
" > "$sm_settings"
fi

# Set language to system language.
lang=${LANG%%_*}
if [[ "$(xmlstarlet select -t -v "//Settings/UserInterfaceLanguage" "$sm_settings")" != "$lang" ]]; then
    xmlstarlet edit -L -u "//Settings/UserInterfaceLanguage" -v "$lang" "$sm_settings"
fi 

# Create initial "test" project to workaround fatal new-session and new-person errors.
proj_name="test"
test_proj_dir="${WINEPREFIX}/drive_c/users/${USER}/Documents/SayMore/${proj_name}"
mkdir -p "$test_proj_dir"
if [[ ! -f "${test_proj_dir}/${proj_name}.sprj" ]]; then
    echo '<?xml version="1.0" encoding="utf-8"?>
<Project>
  <transcriptionFont />
  <freeTranslationFont />
  <AutoSegmentersettings minSegmentLength="0" maxSegmentLength="0" preferrerdPauseLength="0" optimumLengthClampingFactor="0" />
  <Title>test</Title>
  <FundingProjectTitle />
  <ProjectDescription />
  <VernacularISO3CodeAndName />
  <AnalysisISO3CodeAndName />
  <Location />
  <Region />
  <Country>Unspecified</Country>
  <Continent>Unspecified</Continent>
  <ContactPerson />
  <AccessProtocol />
  <DateAvailable />
  <RightsHolder />
  <Depositor />
  <IMDIOutputDirectory />
</Project>' > "${test_proj_dir}/${proj_name}.sprj"
fi
# Create test person.
mkdir -p "${test_proj_dir}/People/New Person"
person_file="${test_proj_dir}/People/New Person/New Person.person"
if [[ ! -f "$person_file" ]]; then
    echo '<?xml version="1.0" encoding="utf-8"?>
<Person>
  <privacyProtection type="string">false</privacyProtection>
</Person>' > "$person_file"
fi
# Create test session.
mkdir -p "${test_proj_dir}/Sessions/New Session"
session_file="${test_proj_dir}/Sessions/New Session/New Session.session"
if [[ ! -f "$session_file" ]]; then
    echo '<?xml version="1.0" encoding="utf-8"?>
<Session version="2.0">
  <genre type="string">&lt;Unknown&gt;</genre>
  <participants type="string"></participants>
  <contributions type="xml" />
</Session>' > "$session_file"
fi

# Force SayMore to open "test" project on 1st run.
test_proj_path="C:\\users\\${USER}\\Documents\\SayMore\\test\\test.sprj"
if [[ -z "$(xmlstarlet select -t -v "//Settings/MRUList/MRUList0" "$sm_settings")" ]]; then
  xmlstarlet edit -L -s "//Settings/MRUList" -t elem -n "MRUList0" -v "$test_proj_path" "$sm_settings"
fi
# # Set FirstTimeRun to False.
# if [[ "$(xmlstarlet select -t -v "//Settings/FirstTimeRun" "$sm_settings")" == 'True' ]]; then
#   xmlstarlet edit -L -u "//Settings/FirstTimeRun" -v "False" "$sm_settings"
# fi
# Set WelcomeDialog values.
if [[ -z "$(xmlstarlet select -t -v "//Settings/WelcomeDialog/windowSettings/state" "$sm_settings")" ]]; then
  xmlstarlet edit -L \
    -s "//Settings/WelcomeDialog" -t attr -n "type" -v "SIL.Windows.Forms.PortableSettingsProvider.FormSettings" \
    -s "//Settings/WelcomeDialog" -t elem -n "windowSettings" \
    -s "//Settings/WelcomeDialog/windowSettings" -t elem -n "state" -v "Normal" \
    -s "//Settings/WelcomeDialog/windowSettings" -t elem -n "bounds" -v "489, 162, 621, 528" \
    -s "//Settings/WelcomeDialog/windowSettings" -t elem -n "dpi" -v "$WINEDPI" \
    "$sm_settings"
fi
# Set ProjectWindow values.
if [[ -z "$(xmlstarlet select -t -v "//Settings/ProjectWindow/windowSettings/state" "$sm_settings")" ]]; then
  xmlstarlet edit -L \
    -s "//Settings/ProjectWindow" -t attr -n "type" -v "SIL.Windows.Forms.PortableSettingsProvider.FormSettings" \
    -s "//Settings/ProjectWindow" -t elem -n "windowSettings" \
    -s "//Settings/ProjectWindow/windowSettings" -t elem -n "state" -v "Maximized" \
    -s "//Settings/ProjectWindow/windowSettings" -t elem -n "bounds" -v "50, 50, 1200, 900" \
    -s "//Settings/ProjectWindow/windowSettings" -t elem -n "dpi" -v "$WINEDPI" \
    "$sm_settings"
fi

# Copy in langtags.json.
sldrcache_dir="${WINEPREFIX}/drive_c/ProgramData/SIL/SldrCache"
mkdir -p "$sldrcache_dir"
base="$SNAP"
if [[ -n "$APP_SHARE_DIR" ]]; then
  base="$APP_SHARE_DIR"
fi
cp -f "${base}/data/langtags.json" "$sldrcache_dir"

# Add duplicate DLL.
sm_dir="${WINEPREFIX}/drive_c/Program Files/SayMore"
cp "${sm_dir}/System.Xml.XmlSerializer.dll" "${sm_dir}/System.XmlSerializers.dll"
xmlstarlet edit -L \
  -s "//configuration/runtime" -t elem -n "assemblyBinding" \
  --var newAB '$prev' \
  -s '$newAB' -t attr -n "xmlns" -v "urn:schemas-microsoft-com:asm.v1" \
  -s '$newAB' -t elem -n "dependentAssembly" \
  --var newDA '$prev' \
  -s '$newDA' -t elem -n "assemblyIdentity" \
  --var newAI '$prev' \
  -s '$newAI' -t attr -n "name" -v "System.XmlSerializers" \
  -s '$newAI' -t attr -n "publicKeyToken" -v "b03f5f7f11d50a3a" \
  -s '$newAI' -t attr -n "culture" -v "neutral" \
  -s '$newDA' -t elem -n "bindingRedirect" \
  --var newBR '$prev' \
  -s '$newBR' -t attr -n "oldVersion" -v "0.0.0.0-4.0.11.0" \
  -s '$newBR' -t attr -n "newVersion" -v "4.0.11.0" \
  "${sm_dir}/Saymore.exe.config"