#!/usr/bin/env bash

if [[ -z "$SNAP_USER_COMMON" ]]; then
    # Not a snap installation.
    exit 0
fi
echo "Checking for user settings to back up."

# Make a backup of user settings.
backup_dir="${SNAP_USER_COMMON}/backups"
user_settings_dir="${SNAP_USER_COMMON}/.wine/drive_c/users/${USER}/AppData/Local/SayMore"
if [[ ! -d "$user_settings_dir" ]]; then
    echo "No user config in $user_settings_dir"
    exit 0
fi
mkdir -p "$backup_dir"
today=$(date -I)
important_files=( "SayMore.settings" )
for name in "${important_files[@]}"; do
    echo "Backing up ${user_settings_dir}/${name}..."
    if [[ -f "${user_settings_dir}/${name}" ]]; then
        cp -f "${user_settings_dir}/${name}" "${backup_dir}/${name}.${today}.bak"
    fi
done

echo "Removing backups older than 90 days."
find "$backup_dir" -type f -mtime +90 -delete
