#!/bin/env bash

# Copy wine-gecko to .cache/wine.
if [[ -n "$SNAP_USER_COMMON" ]]; then
    winecache="${SNAP_USER_COMMON}/.cache/wine"
    mkdir -p "$winecache"
    base="$SNAP"
    if [[ -n "$APP_SHARE_DIR" ]]; then
        base="$APP_SHARE_DIR"
    fi
    cp -f "${base}/data/wine-gecko-2.47.2-x86.msi" "$winecache"
    cp -f "${base}/data/wine-gecko-2.47.2-x86_64.msi" "$winecache"
fi

# Avoid prompt for wine-mono.
export WINEDLLOVERRIDES="mscoree="

# Use local SayMoreInstaller.*.msi if path is set.
if [[ -e "$INSTALL_EXE" ]]; then
    export INSTALL_URL=
fi

# Match SayMore language UI to system locale.
export LC_ALL="$LANG"

# Set default DPI.
if [[ -z "$WINEDPI" ]]; then
    export WINEDPI=108
fi

# Set Winver to 10.
"$WINELOADER" winecfg /v win10
