#!/bin/env bash

# Populate .cache/wine and install wine-gecko.
geckos=( "wine-gecko-2.47.2-x86.msi" "wine-gecko-2.47.2-x86_64.msi" )
winecache="${HOME}/.cache/wine"
for g in "${geckos[@]}"; do
    if [[ -n "$SNAP_USER_COMMON" ]]; then
        winecache="${XDG_CACHE_HOME}/wine"
        mkdir -p "$winecache"
        cp -f "${SNAP}/data/${g}" "$winecache"
    fi
    "$WINELOADER" msiexec /i "${winecache}/${g}"
done

# Use local SayMoreInstaller.*.msi if path is set.
if [[ -e "$INSTALL_EXE" ]]; then
    export INSTALL_URL=
fi

# Match SayMore language UI to system locale.
export LC_ALL="$LANG"

# Set default DPI.
if [[ -z "$WINEDPI" ]]; then
    export WINEDPI=108
fi

# Set Winver to 10.
"$WINELOADER" winecfg /v win10
