#!/bin/env bash

# Remove mscoree from WINEDLLOVERRIDES to allow the app to run.
#    (It's still needed before this point for wineprefix setup, though.)
export WINEDLLOVERRIDES=$(echo "$WINEDLLOVERRIDES" | sed -r 's/[,;]?mscoree[,;]?//')
