name: saymore-unofficial
base: core20 # core22
version: '3.5.1' # matches installer version below
grade: stable
summary: Make common Language Documentation tasks fun and keep you productive.
description: |
  Recording speakers of the world’s languages is fun and rewarding, but keeping all the resulting
  files and meta data organized? Converting files to archive formats? Transcription? Painful.

  That’s why we built SayMore – to make common Language Documentation tasks fun and keep you productive.
confinement: strict
license: MIT
contact: https://github.com/wasta-linux/saymore-snap/issues
issues: https://github.com/wasta-linux/saymore-snap/issues
icon: snap/gui/saymore-unofficial.png
architectures:
  - amd64

environment:
  # LD_PRELOAD: "$LD_PRELOAD:${SNAP}/lib/i386-linux-gnu/bindtextdomain.so"
  TRICKS: "corefonts dotnet462"
  # WINEARCH: "win64"
  WINEARCH: "win32"
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  # WINELOADER: ${SNAP}/wine-platform/wine-stable/bin/wine64
  # WINE: "$WINELOADER" # needed for winetricks

apps:
  saymore-unofficial:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier run-exe
    environment:
      INSTALL_EXE: "data/SayMoreInstaller.3.5.1.msi"
      INSTALL_FLAGS: "/passive"
      # RUN_EXE: "C:/Program Files (x86)/SayMore/SayMore.exe"
      RUN_EXE: "C:/Program Files/SayMore/SayMore.exe"

  init:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier
    environment:
      INIT: '1'

  reinstall-dotnet:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier winetricks -f -q dotnet462

  wine:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier
    environment:
      WINELOADER: "${SNAP}/wine-platform/wine-stable/bin/wine"
      WINE: "$WINELOADER"

  wine64:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier

  winecfg:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier winecfg

  winetricks:
    extensions: [gnome-3-38] # [gnome]
    command: bin/sommelier winetricks

plugs:
  audio-playback:
  desktop:
  desktop-legacy:
  home:
  network:
  removable-media:
  wayland:
  x11:

  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    # default-provider: wine-platform-runtime-core22
    default-provider: wine-platform-runtime-core20
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    # default-provider: wine-platform-7-stable-core22
    default-provider: wine-platform-7-stable-core20

parts:
  data:
    plugin: dump
    source: data/
    organize:
      "*": data/
    stage:
      - data

  debs:
    plugin: nil
    stage-packages:
    - xmlstarlet

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    override-prime: |
      # craftctl default # core22
      snapcraftctl prime # core20

      # Override $WINELOADER to use wine64.
      # sed -r -i 's|(export WINELOADER="\$WINE_PLATFORM/bin/wine)|\164|' bin/sommelier

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # Use tee with yad input to show 
      # Remove annoying yad dialog for interactive MSI install.
      sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier
