name: saymore
base: core22
version: '3.5.1' # matches installer version below
grade: stable
summary: Create language-specific maps, charts, diagrams, and timelines.
description: |
  Map Creator simplifies the creation of language-specific maps, charts, diagrams, and timelines for Bible lessons and world geography.

confinement: strict
architectures:
  - amd64

license: MIT
contact: https://github.com/wasta-linux/saymore-snap/issues

environment:
  TRICKS: "corefonts dotnet462"
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  map-creator:
    extensions: [gnome]
    command: bin/sommelier run-exe
    environment:
      # MapCreator downloads: http://fmosoft.com/download
      INSTALL_EXE: "data/SayMoreInstaller.3.5.1.msi"
      INSTALL_FLAGS: "/passive"
      RUN_EXE: "C:/Program Files (x86)/SayMore/SayMore.exe"

  init:
    extensions: [gnome]
    command: bin/sommelier
    environment:
      INIT: '1'

  reinstall-dotnet:
    extensions: [gnome]
    command: bin/sommelier winetricks -f -q dotnet462

  wine:
    extensions: [gnome]
    command: bin/sommelier

  wine64:
    extensions: [gnome]
    command: bin/sommelier
    environment:
      WINELOADER: "${SNAP}/wine-platform/wine-stable/bin/wine64"
      WINE: "${SNAP}/wine-platform/wine-stable/bin/wine64"

  winecfg:
    extensions: [gnome]
    command: bin/sommelier winecfg

  winetricks:
    extensions: [gnome]
    command: bin/sommelier winetricks

plugs:
  audio-playback:
  desktop:
  desktop-legacy:
  home:
  network:
  # network-bind:
  removable-media:
  x11:
  wayland:

  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core22

parts:
  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    override-prime: |
      snapcraftctl prime

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # Remove annoying yad dialog for interactive MSI install.
      sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier
